# Generated by Django 4.1 on 2022-09-03 14:21

from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ("code",),
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=isbn_field.fields.ISBNField(
                blank=True,
                max_length=28,
                null=True,
                validators=[isbn_field.validators.ISBNValidator],
                verbose_name="ISBN",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("it", "Italian"),
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("pt", "Portuguese"),
                    ("af", "Afrikaans"),
                ],
                max_length=2,
                null=True,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.genre",
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books_from_publsher",
                to="books.publisher",
                verbose_name="publisher",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="code",
            field=models.CharField(max_length=256, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="loan date"
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
    ]
