# Generated by Django 2.0.6 on 2018-06-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_holder', models.CharField(blank=True, max_length=150, verbose_name='loan holder')),
                ('loan_date', models.DateTimeField(blank=True, null=True, verbose_name='loan date')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='loan_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='loan_holder',
        ),
        migrations.AddField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='book'),
        ),
    ]
